[default]
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
via_ir = false
# If enabled, the Solidity compiler is instructed to generate bytecode
# only for the required contracts. This can reduce compile time
# for `forge test`, but is experimental.
sparse_mode = true
revert_strings = "debug"
names = true
sizes = true
