[profile.default]
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
via_ir = false
# debug revert strings looks experimental and fails the CI because of an unexpected error.
revert_strings = "default"
names = true
sizes = true

[profile.gas-report]
fuzz_runs = 0
