"ğŸ‘» aave-v2":
  - contracts/common/*
  - contracts/common/**/*
  - contracts/aave-v2/*
  - contracts/aave-v2/**/*

"ğŸ‘» aave-v3":
  - contracts/common/*
  - contracts/common/**/*
  - contracts/aave-v3/*
  - contracts/aave-v3/**/*

"ğŸŸ¢ compound":
  - contracts/common/*
  - contracts/common/**/*
  - contracts/compound/*
  - contracts/compound/**/*

"ğŸ§® certora":
  - certora/*
  - certora/**/*

"âš™ï¸ ci":
  - .github/actions/*
  - .github/actions/**/*
  - .github/workflows/*
  - .github/workflows/**/*

"ğŸ§ª testing":
  - test-foundry/**/*

"ğŸ¹ fuzzing":
  - test-foundry/fuzzing/**/*
