"ğŸ‘» aave-v2":
  - src/common/*
  - src/common/**/*
  - src/aave-v2/*
  - src/aave-v2/**/*

"ğŸŸ¢ compound":
  - src/common/*
  - src/common/**/*
  - src/compound/*
  - src/compound/**/*

"ğŸ§® certora":
  - certora/*
  - certora/**/*

"âš™ï¸ ci":
  - .github/actions/*
  - .github/actions/**/*
  - .github/workflows/*
  - .github/workflows/**/*

"ğŸ§ª testing":
  - test/**/*

"ğŸ¹ fuzzing":
  - test/fuzzing/**/*
